# Example configuration for Kody-Salesforce Integration
# Copy this file to arguments-sandbox.yaml and update with your credentials

# =========================
# Salesforce Configuration
# =========================
PUBSUB_HOST: api.pubsub.salesforce.com
PUBSUB_PORT: 7443
LOGIN_URL: https://your-org.sandbox.my.salesforce.com
TOPIC: /event/KodyPayment__e

# Authentication (use either username/password OR accessToken/tenantId)
USERNAME: your-username@example.com
PASSWORD: your-password-plus-security-token
TENANT_ID: null
ACCESS_TOKEN: null

# User ID for Salesforce operations
USER_ID: your-user-id

# =========================
# Kody Payment Configuration
# =========================
# Kody gRPC API Hostname (-ap for Asia, -eu for Europe)
KODY_HOSTNAME: grpc-staging-ap.kodypay.com
# Your Kody API Key
KODY_API_KEY: your-kody-api-key-here
# Your Kody Store ID
KODY_STORE_ID: your-store-id-here

# =========================
# Optional Settings
# =========================
NUMBER_OF_EVENTS_TO_PUBLISH: 1
SINGLE_PUBLISH_REQUEST: true
NUMBER_OF_EVENTS_IN_FETCHREQUEST: 5
REPLAY_PRESET: LATEST
PROCESS_CHANGE_EVENT_HEADER_FIELDS: null
MANAGED_SUB_DEVELOPER_NAME: null
MANAGED_SUB_ID: null