# 'arguments-sandbox.yaml' contains the required and optional configurations for running the examples.
#
# Note: Please ensure to specify a value of `null` to all optional configurations when
# you do not wish to specify a value for the same. Some optional configurations will be
# initialised with default values specified below.

# =========================
# Required Configurations:
# =========================
# Pub/Sub API Endpoint
PUBSUB_HOST: api.pubsub.salesforce.com
# Pub/Sub API Host
PUBSUB_PORT: 7443
# Your Salesforce Login URL
LOGIN_URL:

# For authentication, you can use either username/password or accessToken/tenantId types.
# Either one of the combinations is required. Please specify `null` values to the unused type.
# Your Salesforce Username
USERNAME:
# Your Salesforce Password
# PASSWORD = login_password + security_token
PASSWORD:
# Your Salesforce org Tenant ID
TENANT_ID: null
# Your Salesforce Session Token
ACCESS_TOKEN: null

# Locate the Salesforce ID for a User
USER_ID:

# Topic to publish/subscribe to (Required)
TOPIC: /event/KodyPayment__e

# =========================
# Optional Configurations:
# =========================
# ReplayPreset (Accepted Values: {EARLIEST, LATEST (default), CUSTOM})
REPLAY_PRESET: LATEST

# =========================
# Kody Payment Integration Configurations:
# =========================
# Kody gRPC API Hostname, -ap for Asia region and -eu for Europe region
KODY_HOSTNAME: grpc-staging-ap.kodypay.com
# Kody API Key for authentication, used for automation testing only
KODY_API_KEY:
# Kody Store ID for payment requests, used for automation testing only
KODY_STORE_ID:
